stages:
- build
- upload

assembleDebug:
  stage: build
  image: jangrewe/gitlab-ci-android
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export VERSION_CODE=$(date +%s)
    - chmod +x ./gradlew
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/

assembleRelease:
  stage: build
  image: jangrewe/gitlab-ci-android
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export VERSION_CODE=$(date +%s)
    - chmod +x ./gradlew
  script:
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$KEY_ALIAS
      -Pandroid.injected.signing.key.password=$KEY_PASSWORD
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk
      #- CHANGELOG
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/

upload:
  stage: upload
  image: alpine:latest
  script:
    - apk --no-cache add bash curl pwgen unzip
    - curl https://rclone.org/install.sh | /bin/bash
    - bash upload.sh