stages:
  - compile
  - build
  - deploy

compile:
  image: golang:latest
  stage: compile
  script:
    - go test -race $(go list ./... | grep -v /vendor/ | grep -v "/tasktab/agent")
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/tasktab
    - ls -alh $CI_PROJECT_DIR/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/tasktab
  #cache:
  #  paths:
  #    - $GOPATH/src/github.com/
  tags:
    - docker

build:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:pipeline-$CI_PIPELINE_ID --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:pipeline-$CI_PIPELINE_ID
  tags:
    - docker

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache curl
    - curl -X POST -F token=$INFRA_TOKEN -F "ref=master" -F "variables[SERVICE_NAME]=tasktab" -F "variables[SERVICE_VERSION]=pipeline-$CI_PIPELINE_ID" https://gitlab.com/api/v4/projects/6986946/trigger/pipeline
  only:
    - master