stages:
  - compile
  - docker

backend:
  stage: compile
  image: golang:latest
  script:
    - go test -race $(go list ./... | grep -v /vendor/ | grep -v "/tasktab/agent")
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/tasktab
    - ls -alh $CI_PROJECT_DIR/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/tasktab

frontend:
  stage: compile
  image: node:10-alpine
  script:
    - cd frontend
    - apk add yarn
    - yarn install --frozen-lockfile
    - yarn build
    - ls -alh dist
    - mv dist $CI_PROJECT_DIR/new
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - frontend/node_modules
  artifacts:
    paths:
      - new
    expire_in: 1 month

build-and-deploy:
  stage: docker
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:pipeline-$CI_PIPELINE_ID --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:pipeline-$CI_PIPELINE_ID
    - apk add --no-cache bash curl git
    - bash Taskfile.sh deploy-when-master