stages:
- build
- upload

build:
  stage: build
  image: jangrewe/gitlab-ci-android
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/

upload:
  stage: upload
  image: alpine:latest
  script:
    - apk --no-cache add bash curl pwgen unzip
    - mkdir -p /root/.config/
    - curl https://rclone.org/install.sh | /bin/bash
    - echo $RCLONE_CONFIG > /root/.config/rclone
    - ls -alh .
    - find .
    - bash upload.sh