version: "2"
services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  phpredmin:
    image: 'sasanrose/phpredmin'
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 8090:80
    depends_on:
      - redis
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
     - "3307:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=dev
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 15672:15672 # Web GUI
      - 5672:5672 # AMQP
      - 1883:1883 # MQTT
    volumes:
      - "./dev/enabled_plugins:/etc/rabbitmq/enabled_plugins"