version: "2"
services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./dump/:/dump/"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
     - "3307:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=dev