version: "2"
services:
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "3307:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=dev
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-admin:
    image: faktiva/php-redis-admin
    ports:
      - "6380:80"
    depends_on:
      - redis
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis