version: "2"
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  phpredmin:
    image: 'sasanrose/phpredmin'
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 8090:80
    depends_on:
      - redis
  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
  pma:
    image: phpmyadmin
    ports:
     - "3307:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=dev
