name: Build Android .apk
on: [pull_request, push]

# https://github.com/marketplace/actions/build-android-release-apk-when-create-new-tag
jobs:
  Gradle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Enter android dir
        run: cd android
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease
