name: Build Android .apk
on: [ pull_request, push ]

# https://github.com/marketplace/actions/build-android-release-apk-when-create-new-tag
# https://github.community/t/use-working-directory-for-entire-job/16747
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        working-directory: android
        run: chmod +x ./gradlew
      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease
      - name: Save .apk
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
