name: Build Go backend
on: [ pull_request, push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test and build linux binary
        run: bash Taskfile.sh ci-build-backend
      - name: Save binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-binary.zip
          path: cmd/hometab/hometab
