name: Docker image build and push
on: [ pull_request, push ]
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p builds
      - run: cp -r web/templates builds/templates
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: builds/hometab
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: builds/frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push img
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile
          context: .
          push: true
          tags: systemz/hometab:app-git-$GITHUB_SHA
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
