name: Webapp dev build
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test and build linux binary
        run: bash Taskfile.sh ci-build-backend
      - name: Save binary
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: cmd/hometab/hometab
  frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14.x LTS
        uses: actions/setup-node@v1
        with:
          # https://nodejs.org/en/about/releases/
          node-version: 14.x
      - name: Build frontend
        run: bash Taskfile.sh ci-build-frontend
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/dist
