name: Web app release build
on:
  push:
    branches:
      - master
jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test and build linux binary
        run: bash Taskfile.sh ci-build-backend
      - name: Save binary
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: cmd/hometab/hometab
  frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14.x LTS
        uses: actions/setup-node@v1
        with:
          # https://nodejs.org/en/about/releases/
          node-version: 14.x
      - name: Build frontend
        run: bash Taskfile.sh ci-build-frontend
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/dist
  docker-image:
    needs: [backend, frontend]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p builds
      - run: cp -r web/templates builds/templates
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: builds/hometab
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: builds/frontend
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
          password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
      - name: Build and push img
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile
          context: builds
          push: true
          tags: systemz/hometab:app-git-${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
